### ISSUE TITLE
[CONTRIB] la revanche des geeks

### ISSUE THREAD

**Issue by sofianinho** [abousselmi/nabla#2]
# Pour les Humains:

## Titre de l'article
SO FOOT #164: La revanche des geeks

## Lien de l'article
https://rmc.bfmtv.com/mediaplayer/audio/rmc-2703-l-afterfoot-22h-23h-463139.html

## Lien canonique
https://rmc.bfmtv.com/

## Tags
statistics,sport,data science,futur

## Résumé de l'article
Le football est-il une science exacte? et plein d'autres questions dans ce podcast et magazine
+ Pour Rasmus Ankersen, jeune président du club, tout est une question de modèles mathématiques et d’analyse de données. 
+ Prozone. Qui est Ram Mylvaganam, le créateur de Prozone, le logiciel que la Premier League s’est arraché à l’orée des années 2000 ?
+ Opta. On a passé quelques heures dans leurs locaux à Leeds...
+ Hal Robson-Kanu. L’attaquant de WBA a vu dans la blockchain le moyen de changer le visage du football et a carrément monté une start-up qui pourrait le rendre milliardaire. 

# Version finale

```console
---
layout: post
title: "Sport (Football): La revanche des geeks (écouter vers 29:15)"
link: "https://rmc.bfmtv.com/mediaplayer/audio/rmc-2703-l-afterfoot-22h-23h-463139.html"
canonical: "rmc.bfmtv.com"
tags: [statistics, sport, data science, futur]
excerpt: "Le football est-il une science exacte? et plein d'autres questions dans ce podcast et magazine (So Foot n°164)"
comments: true
---
```

**Comment by abousselmi** [comment]
Thank you @sofianinho The post is published.
